# Generated by Django 5.2 on 2025-04-10 20:03

import s2s.db_models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s2s", "0002_alter_scenarios_day_of_week1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=s2s.db_models.profile.profile_picture_path,
            ),
        ),
    ]
