# Generated by Django 5.2 on 2025-04-10 20:09

import s2s.db_models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s2s", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/media/default_profile.jpg",
                upload_to=s2s.db_models.profile.profile_picture_path,
            ),
        ),
    ]
