
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
    /(
        \.eggs/|
        \.git/|
        \.hg/|
        \.mypy_cache/|
        \.tox/|
        \.venv/|
        \.svn/|
        _build/|
        buck-out/|
        build/|
        dist/
    )|
    ^docs/|
    ^examples/
'''
